INSERT INTO `SITE_DB`.`system_countries` (`id`, `name`, `phone_countrycode`, `phone_format`, `language`, `currency`)
VALUES
	('AW','Aruba','','','EN','USD'),
	('AF','Afghanistan','','','EN','USD'),
	('AO','Angola','','','EN','USD'),
	('AL','Albania','','','EN','EUR'),
	('AD','Andorra','','','EN','EUR'),
	('AE','United Arab Emirates','','','EN','USD'),
	('AR','Argentina','','','EN','USD'),
	('AM','Armenia','','','EN','USD'),
	('AS','American Samoa','','','EN','USD'),
	('AG','Antigua and Barbuda','','','EN','USD'),
	('AU','Australia','','','EN','USD'),
	('AT','Austria','','','EN','EUR'),
	('AZ','Azerbaijan','','','EN','USD'),
	('BI','Burundi','','','EN','USD'),
	('BE','Belgium','','','EN','EUR'),
	('BJ','Benin','','','EN','USD'),
	('BF','Burkina Faso','','','EN','USD'),
	('BD','Bangladesh','','','EN','USD'),
	('BG','Bulgaria','','','EN','EUR'),
	('BH','Bahrain','','','EN','USD'),
	('BS','Bahamas, The','','','EN','USD'),
	('BA','Bosnia and Herzegovina','','','EN','EUR'),
	('BY','Belarus','','','EN','EUR'),
	('BZ','Belize','','','EN','USD'),
	('BM','Bermuda','','','EN','USD'),
	('BO','Bolivia','','','EN','USD'),
	('BR','Brazil','','','EN','USD'),
	('BB','Barbados','','','EN','USD'),
	('BN','Brunei Darussalam','','','EN','USD'),
	('BT','Bhutan','','','EN','USD'),
	('BW','Botswana','','','EN','USD'),
	('CF','Central African Republic','','','EN','USD'),
	('CA','Canada','','','EN','USD'),
	('CH','Switzerland','','','EN','EUR'),
	('JG','Channel Islands','','','EN','USD'),
	('CL','Chile','','','EN','USD'),
	('CN','China','','','EN','USD'),
	('CI','Cote d\'Ivoire','','','EN','USD'),
	('CM','Cameroon','','','EN','USD'),
	('CD','Congo, Dem. Rep.','','','EN','USD'),
	('CG','Congo, Rep.','','','EN','USD'),
	('CO','Colombia','','','EN','USD'),
	('KM','Comoros','','','EN','USD'),
	('CV','Cabo Verde','','','EN','USD'),
	('CR','Costa Rica','','','EN','USD'),
	('CU','Cuba','','','EN','USD'),
	('CW','Curacao','','','EN','USD'),
	('KY','Cayman Islands','','','EN','USD'),
	('CY','Cyprus','','','EN','EUR'),
	('CZ','Czech Republic','','','EN','EUR'),
	('DE','Germany','','','EN','EUR'),
	('DJ','Djibouti','','','EN','USD'),
	('DM','Dominica','','','EN','USD'),
	('DK','Danmark','45','#### ####','EN','DKK'),
	('DO','Dominican Republic','','','EN','USD'),
	('DZ','Algeria','','','EN','USD'),
	('EC','Ecuador','','','EN','USD'),
	('EG','Egypt, Arab Rep.','','','EN','USD'),
	('ER','Eritrea','','','EN','USD'),
	('ES','Spain','','','EN','EUR'),
	('EE','Estonia','','','EN','EUR'),
	('ET','Ethiopia','','','EN','USD'),
	('FI','Finland','','','EN','EUR'),
	('FJ','Fiji','','','EN','USD'),
	('FR','France','','','EN','EUR'),
	('FO','Faroe Islands','','','EN','USD'),
	('FM','Micronesia, Fed. Sts.','','','EN','USD'),
	('GA','Gabon','','','EN','USD'),
	('GB','United Kingdom','','','EN','EUR'),
	('GE','Georgia','','','EN','EUR'),
	('GH','Ghana','','','EN','USD'),
	('GI','Gibraltar','','','EN','EUR'),
	('GN','Guinea','','','EN','USD'),
	('GM','Gambia, The','','','EN','USD'),
	('GW','Guinea-Bissau','','','EN','USD'),
	('GQ','Equatorial Guinea','','','EN','USD'),
	('GR','Greece','','','EN','EUR'),
	('GD','Grenada','','','EN','USD'),
	('GL','Greenland','','','EN','DKK'),
	('GT','Guatemala','','','EN','USD'),
	('GU','Guam','','','EN','USD'),
	('GY','Guyana','','','EN','USD'),
	('HK','Hong Kong SAR, China','','','EN','USD'),
	('HN','Honduras','','','EN','USD'),
	('HR','Croatia','','','EN','EUR'),
	('HT','Haiti','','','EN','USD'),
	('HU','Hungary','','','EN','EUR'),
	('ID','Indonesia','','','EN','USD'),
	('IM','Isle of Man','','','EN','EUR'),
	('IN','India','','','EN','USD'),
	('IE','Ireland','','','EN','EUR'),
	('IR','Iran, Islamic Rep.','','','EN','USD'),
	('IQ','Iraq','','','EN','USD'),
	('IS','Iceland','','','EN','EUR'),
	('IL','Israel','','','EN','USD'),
	('IT','Italy','','','EN','EUR'),
	('JM','Jamaica','','','EN','USD'),
	('JO','Jordan','','','EN','USD'),
	('JP','Japan','','','EN','USD'),
	('KZ','Kazakhstan','','','EN','USD'),
	('KE','Kenya','','','EN','USD'),
	('KG','Kyrgyz Republic','','','EN','USD'),
	('KH','Cambodia','','','EN','USD'),
	('KI','Kiribati','','','EN','USD'),
	('KN','St. Kitts and Nevis','','','EN','USD'),
	('KR','Korea, Rep.','','','EN','USD'),
	('KW','Kuwait','','','EN','USD'),
	('LA','Lao PDR','','','EN','USD'),
	('LB','Lebanon','','','EN','USD'),
	('LR','Liberia','','','EN','USD'),
	('LY','Libya','','','EN','USD'),
	('LC','St. Lucia','','','EN','USD'),
	('LI','Liechtenstein','','','EN','EUR'),
	('LK','Sri Lanka','','','EN','USD'),
	('LS','Lesotho','','','EN','USD'),
	('LT','Lithuania','','','EN','EUR'),
	('LU','Luxembourg','','','EN','EUR'),
	('LV','Latvia','','','EN','EUR'),
	('MO','Macao SAR, China','','','EN','USD'),
	('MF','St. Martin (French part)','','','EN','USD'),
	('MA','Morocco','','','EN','USD'),
	('MC','Monaco','','','EN','EUR'),
	('MD','Moldova','','','EN','EUR'),
	('MG','Madagascar','','','EN','USD'),
	('MV','Maldives','','','EN','USD'),
	('MX','Mexico','','','EN','USD'),
	('MH','Marshall Islands','','','EN','USD'),
	('MK','Macedonia, FYR','','','EN','EUR'),
	('ML','Mali','','','EN','USD'),
	('MT','Malta','','','EN','EUR'),
	('MM','Myanmar','','','EN','USD'),
	('ME','Montenegro','','','EN','EUR'),
	('MN','Mongolia','','','EN','USD'),
	('MP','Northern Mariana Islands','','','EN','USD'),
	('MZ','Mozambique','','','EN','USD'),
	('MR','Mauritania','','','EN','USD'),
	('MU','Mauritius','','','EN','USD'),
	('MW','Malawi','','','EN','USD'),
	('MY','Malaysia','','','EN','USD'),
	('NA','Namibia','','','EN','USD'),
	('NC','New Caledonia','','','EN','USD'),
	('NE','Niger','','','EN','USD'),
	('NG','Nigeria','','','EN','USD'),
	('NI','Nicaragua','','','EN','USD'),
	('NL','Netherlands','','','EN','EUR'),
	('NO','Norway','','','EN','EUR'),
	('NP','Nepal','','','EN','USD'),
	('NR','Nauru','','','EN','USD'),
	('NZ','New Zealand','','','EN','USD'),
	('OM','Oman','','','EN','USD'),
	('PK','Pakistan','','','EN','USD'),
	('PA','Panama','','','EN','USD'),
	('PE','Peru','','','EN','USD'),
	('PH','Philippines','','','EN','USD'),
	('PW','Palau','','','EN','USD'),
	('PG','Papua New Guinea','','','EN','USD'),
	('PL','Poland','','','EN','EUR'),
	('PR','Puerto Rico','','','EN','USD'),
	('KP','Korea, Dem. People’s Rep.','','','EN','USD'),
	('PT','Portugal','','','EN','EUR'),
	('PY','Paraguay','','','EN','USD'),
	('PS','West Bank and Gaza','','','EN','USD'),
	('PF','French Polynesia','','','EN','USD'),
	('QA','Qatar','','','EN','USD'),
	('RO','Romania','','','EN','EUR'),
	('RU','Russian Federation','','','EN','EUR'),
	('RW','Rwanda','','','EN','USD'),
	('SA','Saudi Arabia','','','EN','USD'),
	('SD','Sudan','','','EN','USD'),
	('SN','Senegal','','','EN','USD'),
	('SG','Singapore','','','EN','USD'),
	('SB','Solomon Islands','','','EN','USD'),
	('SL','Sierra Leone','','','EN','USD'),
	('SV','El Salvador','','','EN','USD'),
	('SM','San Marino','','','EN','EUR'),
	('SO','Somalia','','','EN','USD'),
	('RS','Serbia','','','EN','EUR'),
	('SS','South Sudan','','','EN','USD'),
	('ST','Sao Tome and Principe','','','EN','USD'),
	('SR','Suriname','','','EN','USD'),
	('SK','Slovak Republic','','','EN','EUR'),
	('SI','Slovenia','','','EN','EUR'),
	('SE','Sweden','','','EN','EUR'),
	('SZ','Swaziland','','','EN','USD'),
	('SX','Sint Maarten (Dutch part)','','','EN','USD'),
	('SC','Seychelles','','','EN','USD'),
	('SY','Syrian Arab Republic','','','EN','USD'),
	('TC','Turks and Caicos Islands','','','EN','USD'),
	('TD','Chad','','','EN','USD'),
	('TG','Togo','','','EN','USD'),
	('TH','Thailand','','','EN','USD'),
	('TJ','Tajikistan','','','EN','USD'),
	('TM','Turkmenistan','','','EN','USD'),
	('TL','Timor-Leste','','','EN','USD'),
	('TO','Tonga','','','EN','USD'),
	('TT','Trinidad and Tobago','','','EN','USD'),
	('TN','Tunisia','','','EN','USD'),
	('TR','Turkey','','','EN','EUR'),
	('TV','Tuvalu','','','EN','USD'),
	('TW','Taiwan, China','','','EN','USD'),
	('TZ','Tanzania','','','EN','USD'),
	('UG','Uganda','','','EN','USD'),
	('UA','Ukraine','','','EN','EUR'),
	('UY','Uruguay','','','EN','USD'),
	('US','United States','','','EN','USD'),
	('UZ','Uzbekistan','','','EN','USD'),
	('VC','St. Vincent and the Grenadines','','','EN','USD'),
	('VE','Venezuela, RB','','','EN','USD'),
	('VG','British Virgin Islands','','','EN','USD'),
	('VI','Virgin Islands (U.S.)','','','EN','USD'),
	('VN','Vietnam','','','EN','USD'),
	('VU','Vanuatu','','','EN','USD'),
	('WS','Samoa','','','EN','USD'),
	('XK','Kosovo','','','EN','EUR'),
	('YE','Yemen, Rep.','','','EN','USD'),
	('ZA','South Africa','','','EN','USD'),
	('ZM','Zambia','','','EN','USD'),
	('ZW','Zimbabwe','','','EN','USD');
